# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

{{ if .Values.deployObjectProviderApi }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-objectproviderapi
spec:
  replicas: 3
  minReadySeconds: 1 # Default 0
  progressDeadlineSeconds: 60 # Default 600 - Allow for shorter time before fail
  revisionHistoryLimit: 5 # Allow keeping 5 deployments history for rollback
  strategy:
    type: RollingUpdate # This is default
    rollingUpdate:
      maxSurge: 1 # Default 25% - number allowed to go over during update
      maxUnavailable: 1 # Default 25% - number allowed to go down at a time
  selector:
    matchLabels:
      app: {{ .Release.Name }}-objectproviderapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-objectproviderapi
    spec:
      containers:
      - name: exhub-objectproviderapi
        image: {{ .Values.images.repository }}/{{ .Values.images.objectProviderApi.imageName }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: 80
          name: api
        - containerPort: 443
          name: apis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-objectproviderapi
  labels: 
    app: {{ .Release.Name }}-objectproviderapi
spec:
  ports:
  - port: 80
    name: api
  - port: 443
    name: apis
  selector:
    app: {{ .Release.Name }}-objectproviderapi
{{ end }}