apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-extensionmgmtapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-extensionmgmtapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-extensionmgmtapi
    spec:
      containers:
      - name: exhub-extensionmgmtapi
        image: {{ .Values.images.repository }}/{{ .Values.images.extensionMgmtApi.imageName }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        env:
        - name: EXHUB_CONFIG_BLOB_STORAGE_CONNECTION_STRING
          value: {{ .Values.configuration.storageConnectionString | quote }}
        - name: EXHUB_CONFIG_BLOB_STORAGE_CONTAINER_NAME
          value: {{ .Values.configuration.containerName | quote }}
        - name: EXHUB_CONFIG_BLOB_STORAGE_BLOB_NAME
          value: {{ .Values.configuration.extensionMgmtApi.blobName | quote }}
        ports:
        - containerPort: 80
          name: api
        - containerPort: 443
          name: apis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-extensionmgmtapi
  labels: 
    app: {{ .Release.Name }}-extensionmgmtapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: api
  - port: 443
    name: apis
  selector:
    app: {{ .Release.Name }}-extensionmgmtapi