# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Default values for extension-hubs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployExecutionAdapterApi: false
deployExtensionServiceApi: false
deployObjectProviderApi: false

images:
  repository: ""
  pullPolicy: Always
  catalogApi:
    imageName: "xhub-catalogapi:latest"
  executionApi:
    imageName: "xhub-executionapi:latest"
  extensionMgmtApi:
    imageName: "xhub-extensionmgmtapi:latest"
  executionConsole:
    imageName: "xhub-executionconsole:latest"
  executionAdapterApi:
    imageName: "xhub-executionadapterapi:latest"
  extensionServiceApi:
    imageName: "xhub-extensionserviceapi:latest"
  objectProviderApi:
    imageName: "xhub-objectproviderapi:latest"

configuration:
  storageConnectionString: ""
  containerName: "configuration"
  catalogApi:
    blobName: "appsettings-catalogapi.json"
  executionApi:
    blobName: "appsettings-execapi.json"
  extensionMgmtApi:
    blobName: "appsettings-extensionmgmtapi.json"
  executionConsole:
    blobName: "appsettings-execconsole.json"