trigger: none
pr: none

resources:
- repo: self
    
variables:
  tag: '$(Build.BuildId)'
  'rgName': 'exthub-use2-rg-prod'
  'location': 'eastus2'
  'aksK8sVersion': '1.16.7'
    
stages:
- stage: Deploy
  displayName: Deploy Infra-as-Code
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure-Subscription'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(rgName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: 'src/draco/infra/ArmTemplate/exthub/exthub-deploy.json'
        overrideParameters: '-aksK8sVersion $(aksK8sVersion) -aksServicePrincipalClientId $(aksClientId) -aksServicePrincipalClientSecret $(aksClientSecret)'
        deploymentMode: 'Incremental'