trigger: 
    branches: 
      include: 
      - master
    paths:
      include:
      - src/draco/infra/ArmTemplate/exthub/*
pr:
    branches:
      include:
      - master
    paths:
      include:
      - src/draco/infra/ArmTemplate/exthub/*
    
resources:
- repo: self
    
variables:
  tag: '$(Build.BuildId)'
  'rgName': 'exthub-use2-rg-test'
  'location': 'eastus2'
  'aksK8sVersion': '1.16.7'
    
stages:
- stage: Test
  displayName: Test Infra-as-Code
  jobs:  
  - job: Test
    displayName: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure-Subscription'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(rgName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: 'src/draco/infra/ArmTemplate/exthub/exthub-deploy.json'
        overrideParameters: '-aksK8sVersion $(aksK8sVersion) -aksServicePrincipalClientId $(aksClientId) -aksServicePrincipalObjectId $(aksObjectId) -aksServicePrincipalClientSecret $(aksClientSecret)'
        deploymentMode: 'Validation'
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        action: 'DeleteRG'
        resourceGroupName: $(rgName)
        azureResourceManagerConnection: 'Azure-Subscription'
        location: $(location)
