# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: extensionecho
spec:
  replicas: 1
  minReadySeconds: 1 # Default 0
  progressDeadlineSeconds: 60 # Default 600 - Allow for shorter time before fail
  revisionHistoryLimit: 5 # Allow keeping 5 deployments history for rollback
  strategy:
    type: RollingUpdate # This is default
    rollingUpdate:
      maxSurge: 1 # Default 25% - number allowed to go over during update
      maxUnavailable: 1 # Default 25% - number allowed to go down at a time
  selector:
    matchLabels:
      app: extensionecho
  template:
    metadata:
      labels:
        app: extensionecho
    spec:
      containers:
      - name: extension-echo:latest
        image: $ACR_NAME.azurecr.io/extension-echo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: api
        - containerPort: 443
          name: apis
apiVersion: v1
kind: Service
metadata:
  name: extensionecho
  labels: 
    app: extensionecho
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: api
  - port: 443
    name: apis
  selector:
    app: extensionecho