# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-echo
  template:
    metadata:
      labels:
        app: sample-echo
    spec:
      containers:
      - name: echo
        image: dracodv2vytrugocvmacr.azurecr.io/echo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: api
        - containerPort: 443
          name: apis
---
apiVersion: v1
kind: Service
metadata:
  name: sample-echo
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks-subnet"
  labels: 
    app: sample-echo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: api
  - port: 443
    name: apis
  selector:
    app: sample-echo
