# Note that Dockerfiles are currently written using root source directory as
# build context, but live in respective sub-directories
version: "3.4"
services:
  catalog.api:
    build:
      context: ./
      dockerfile: ./Catalog.Api/Dockerfile
    image: catalog.api
    container_name: catalog.api
    restart: 'no'
    environment:
      - TZ=${TZ}
      - EXHUB_CONFIG_BLOB_STORAGE_BLOB_NAME=appsettings-catalogapi.json
      - EXHUB_CONFIG_BLOB_STORAGE_CONTAINER_NAME=configuration
      - EXHUB_CONFIG_BLOB_STORAGE_CONNECTION_STRING=${EXHUB_CONFIG_BLOB_STORAGE_CONNECTION_STRING}
    ports:
    - 8325:80
  extensionmanagement.api:
    build:
      context: ./
      dockerfile: ./ExtensionManagement.Api/Dockerfile
    image: extensionmanagement.api
    container_name: extensionmanagement.api
    restart: 'no'
    environment:
      - TZ=${TZ}
      - EXHUB_CONFIG_BLOB_STORAGE_BLOB_NAME=appsettings-extensionmgmtapi.json
      - EXHUB_CONFIG_BLOB_STORAGE_CONTAINER_NAME=configuration
      - EXHUB_CONFIG_BLOB_STORAGE_CONNECTION_STRING=${EXHUB_CONFIG_BLOB_STORAGE_CONNECTION_STRING}
    ports:
      - 8326:80
  execution.api:
    build:
      context: ./
      dockerfile: ./Execution.Api/Dockerfile
    image: execution.api
    container_name: execution.api
    restart: 'no'
    environment:
      - TZ=${TZ}
      - EXHUB_CONFIG_BLOB_STORAGE_BLOB_NAME=appsettings-execapi.json
      - EXHUB_CONFIG_BLOB_STORAGE_CONTAINER_NAME=configuration
      - EXHUB_CONFIG_BLOB_STORAGE_CONNECTION_STRING=${EXHUB_CONFIG_BLOB_STORAGE_CONNECTION_STRING}
    ports:
      - 8327:80
  executionadapter.api:
    build:
      context: ./
      dockerfile: ./ExecutionAdapter.Api/Dockerfile
    image: executionadapter.api
    container_name: executionadapter.api
    restart: 'no'
    environment:
      - TZ=${TZ}
    ports:
      - 8328:80
  executionadapter.consolehost:
    build:
      context: ./
      dockerfile: ./ExecutionAdapter.ConsoleHost/Dockerfile
    image: executionadapter.consolehost
    container_name: executionadapter.consolehost
    restart: 'no'
    environment:
      - TZ=${TZ}
      - EXHUB_CONFIG_BLOB_STORAGE_BLOB_NAME=appsettings-execconsole.json
      - EXHUB_CONFIG_BLOB_STORAGE_CONTAINER_NAME=configuration
      - EXHUB_CONFIG_BLOB_STORAGE_CONNECTION_STRING=${EXHUB_CONFIG_BLOB_STORAGE_CONNECTION_STRING}
